### ISSUE TITLE
There is an arbitrary limitation of 10 mutations in a transaction

### ISSUE THREAD

**Issue by valpackett** [kitsonk/kv-toolbox#2]
Due to https://github.com/denoland/deno/issues/19284 this module currently has a "640 KB should be enough for everybody" situation…

A larger blob fails on this commit:

https://github.com/kitsonk/kv-toolbox/blob/ad4d925a64142bff487a98780536592815e32168/blob.ts#L232

**Comment by kitsonk** [comment]
OK, I was unaware of the limitation. Will batch the commits then.

**Comment by kitsonk** [comment]
The feature to work around this limitation is available in version [0.0.3](https://deno.land/x/kv_toolbox@0.0.3).
