### ISSUE TITLE
Support for `expireIn` option

### ISSUE THREAD

**Issue by yudai-nkt** [kitsonk/kv-toolbox#3]
I want to store 64+KiB images to KV with TTL, but `kv-toolbox` currently doesn't have an interface with the underlying Deno KV API (https://github.com/denoland/deno/pull/20091).

**Comment by yudai-nkt** [comment]
uh, I wasn't aware this option is currently available only in the CLI: https://deno.com/blog/kv-open-beta#key-ttl-with-expirein. Sorry if the PR is a bit hasty.

**Comment by kitsonk** [comment]
Thanks for raising the issue.

I will think about how it can be supported intelligently.

**Comment by yudai-nkt** [comment]
Thanks for the response. Feel free to close #4 if it's not a path you want to take.

**Comment by kitsonk** [comment]
Available in 0.0.4.
